TestingHomework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homework.urls')),
    path('users/', include('users.urls')),
    path('social/', include('UserMessages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

homework/urls.py
from django.urls import path
from django.conf import settings
from . import views

urlpatterns = [
    path("", views.Home.as_view(), name='homework-home'),
    path("tomorrow/", views.Tomorrow.as_view(), name='homework-tomorrow'),
    path("all/", views.All.as_view(), name='homework-all'),
    path("add/", views.addAssignment, name='homework-add'),
    path("assignment/<int:homeworkId>/", views.assignmentInfo, name='homework-assignment'),
]

if settings.DEBUG:
    urlpatterns.append(path("vote/<str:code>", views.surveyInfo, name='homework-surveyInfo'))
    urlpatterns.append(path("vote/", views.surveyEntry, name='homework-surveyEntry'))

users/urls.py
from django.urls import path
from django.contrib.auth import views as account_views
from . import views

urlpatterns = [
    path("register/", views.register, name='users-register'),
    path(
        "login/",  
        account_views.LoginView.as_view(
            template_name='users/login.html', 
            extra_context={"loginActive": True, "title": "Влизане"}
        ), 
        name="users-login"
    ),
    path("logout/", views.LogoutView.as_view(), name='users-logout'),
    path("<int:profileId>", views.profileHomework, name="users-profileinfo"),
    path("backup", views.backup, name="users-backup")
]

homework/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.mail import send_mail, EmailMessage, get_connection
from django.contrib.auth.models import User
import smtplib
from email.message import EmailMessage

# Create your models here.

# TODO: Съобщенията трябва да могат да се добавят и чрез отделна страница. Засега може само от администраторския панел
class Messages(models.Model):
    messageLabel = models.CharField(max_length=255, verbose_name="Заглавие")
    messageText = models.TextField(verbose_name="Текст")
    messageImportance = models.IntegerField(verbose_name="Ниво на съобщението", validators=[MinValueValidator(-1), MaxValueValidator(1)])
    dateBegin = models.DateTimeField(verbose_name="Дата на появяне")
    dateEnd = models.DateTimeField(verbose_name="Дата на изчезване")

    def __str__(self):
        return self.messageLabel
    class Meta:
        verbose_name = "Съобщение"
        verbose_name_plural = "Съобщения"
    # def save(self, *args, **kwargs):
    #     is_new = self.pk is None 
    #     super().save(*args, **kwargs)
    #     if is_new:
    #         allUsers = User.objects.all()
    #         emails = []
    #         for user in allUsers:
    #             if user.studentprofile.sendEmails == True:
    #                 emails.append(user.email)
    #         subject = f"{self.messageLabel}"
    #         html_content = f"""
    #         <h1>Ново съобщение на сайта</h1>
    #         <h2>Администраторски код за важност: {self.messageImportance}</h2>
    #         <p style="white-space: pre-wrap;">{self.messageText}</p>
    #         """
    #         from_email = "Пощата на 9.'ж' клас <nikolaibanev123@gmail.com>"
    #         msg = EmailMessage()
    #         msg["Subject"] = subject
    #         msg["From"] = from_email
    #         msg.add_alternative(html_content, subtype='html')
    #         with smtplib.SMTP("smtp.gmail.com", 587) as server:
    #             server.starttls()
    #             server.login("nikolaibanev123@gmail.com", "nupj vekf ihqo djbm")
    #             server.send_message(msg, to_addrs=emails)

# *Готово
class Subject(models.Model):
    name = models.CharField(max_length=255, verbose_name="Предмет")
    teacher = models.CharField(max_length=255, verbose_name="Учител")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Предмет"
        verbose_name_plural = "Предмети"

class AssignmentType(models.TextChoices):
    TESTWRITE = "Писмено изпитване", "Писмено изпитване"
    TESTORAL = "Устно изпитване", "Устно изпитване"
    TESTENTRY = "Входно равнище", "Входно равнище"
    TESTEXIT = "Изходно равнище", "Изходно равнище"
    HOMEWORK = "Домашна работа", "Домашна работа"
    PROJECT = "Проект", "Проект"

class Assignment(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name="Предмет")
    description = models.TextField(verbose_name="Описание")
    addedBy = models.ForeignKey(User, null=True, default=None, on_delete=models.CASCADE, verbose_name="Добавен от потребител")
    dateAdded = models.DateTimeField("Добавено на", auto_now_add=True)
    dateDue = models.DateField(verbose_name="Крайна дата")
    typeOfAssignment = models.CharField(max_length=255, verbose_name="Тип на заданието", choices=AssignmentType.choices, default=AssignmentType.HOMEWORK)

    def __str__(self):
        return self.description
    class Meta:
        verbose_name = "Задание"
        verbose_name_plural = "Задания"

class DutyStudent(models.Model):
    userConn = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Потребител")
    dateBegin = models.DateField(verbose_name="Начало на дежурство")
    dateEnd = models.DateField(verbose_name="Край на дежурство")

    def __str__(self):
        begin = self.dateBegin.strftime("%d.%m.%Y") if self.dateBegin else "?"
        end = self.dateEnd.strftime("%d.%m.%Y") if self.dateEnd else "?"
        return f"Дежурство на номер {self.userConn.studentprofile.classNumber} от {begin} до {end}"
    class Meta:
        verbose_name = "Дежурство"
        verbose_name_plural = "Дежурства"

class Question(models.Model):
    question = models.CharField(max_length=255)
    beginDateTime = models.DateTimeField()
    endDateTime = models.DateTimeField()
    questionCode = models.CharField(max_length=6, unique=True)

class Choices(models.Model):
    questionConn = models.ForeignKey(Question, on_delete=models.CASCADE)
    choiceText = models.CharField(max_length=255)

class Vote(models.Model):
    userConn = models.ForeignKey(User, on_delete=models.CASCADE)
    questionConn = models.ForeignKey(Question, on_delete=models.CASCADE)
    choiceConn = models.ForeignKey(Choices, on_delete=models.CASCADE)

homework/forms.py
from django import forms
from . import models
from django.contrib.admin.widgets import AdminDateWidget, AdminSplitDateTime

class AssignmentAdd(forms.ModelForm):
    
    class Meta:
        model = models.Assignment
        fields = ["subject", "description", "dateDue", "typeOfAssignment"] 
        widgets = {
            "dateDue": forms.DateInput(attrs={"type": "date"})
        }  

homework/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.contrib.auth.models import User
from django.views import View
from django.utils import timezone
from django.core.paginator import Paginator
from django.http import HttpResponse, Http404
from datetime import timedelta
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required, user_passes_test
from . import forms
from . import models

# Create your views here.

# *Засега е готово, май :)
class Home(View):
    def get(self, request):
        now = timezone.now()
        activeMessages = models.Messages.objects.filter(dateBegin__lte=now, dateEnd__gte=now)
        context = {
            "homeActive": True,
            "activeMessages": activeMessages,
            "title": "Начална страница"
        }
        return render(request, "homework/home.html", context)

class Tomorrow(ListView):
    model = models.Assignment
    template_name = "homework/tomorrow.html"
    context_object_name = "assignments"
    paginate_by = 20
    def get_queryset(self):
        today = timezone.localdate()
        tomorrow = today + timedelta(days=1)
        return (
            models.Assignment.objects
            .filter(dateDue__in=[today, tomorrow])
            .order_by("-dateDue")
        )
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tomorrowActive'] = True
        context['title'] = "Утрешни задания"
        return context
class All(ListView):
    model = models.Assignment
    template_name = "homework/all.html"
    context_object_name = "assignments"
    paginate_by = 10
    def get_queryset(self):
        return models.Assignment.objects.all().order_by("-dateDue")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allActive'] = True
        context['title'] = "Всички задания"
        return context

def addAssignment(request):
    today = timezone.now().date()
    activeDuties = models.DutyStudent.objects.filter(
        dateBegin__lte=today,
        dateEnd__gte=today
    )
    allUsers = User.objects.select_related("studentprofile").order_by("studentprofile__classNumber")
    if request.method == "POST":
        form = forms.AssignmentAdd(request.POST)
        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.addedBy = request.user
            assignment.save()
            messages.success(request, f"Заданието беше добавено ")
            return redirect("homework-home")
        else:
            return render(request, "homework/add.html", {"form": form})
    else:
        form = forms.AssignmentAdd()
    return render(request, "homework/add.html", {"form": form, "activeDuties": activeDuties, "users":allUsers, "addActive": True, "title": "Добавяне на задание"})



def assignmentInfo(request, homeworkId):
    today = timezone.now().date()
    activeDuties = models.DutyStudent.objects.filter(
        dateBegin__lte=today,
        dateEnd__gte=today
    )
    result = models.Assignment.objects.get(id=homeworkId)
    if request.method == "POST":
        form = forms.AssignmentAdd(request.POST,instance=result)
        if form.is_valid():
            messages.success(request, f"Заданието беше актуализирано")
            form.save()
            return redirect("homework-home")
        else:
            return render(request, "homework/assignment.html", {"form": form})
    else:
        form = forms.AssignmentAdd(instance=result)
    return render(request, "homework/assignment.html", context={"assignment": result, "duties": activeDuties,"form": form, "title": f"Задание №{result.id}"})

def isPartOfClass(user):
    if user.studentprofile.classNumber >= 1 and user.studentprofile.classNumber <= 25:
        return True
    else:
        return False

@login_required
@user_passes_test(isPartOfClass, redirect_field_name="homework-home")
def surveyInfo(request, code):
    if request.method == "POST":
        question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "",
            {
                "question": question,
                "error_message": "Не беше избран",
            },
        )
    else:
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    if request.method == "GET":
        try:
            questionInfo = models.Question.objects.get(questionCode=code)
        except models.Question.DoesNotExist:
            raise Http404("Този код не е намерен!")
        return render(request, "homework/surveyInfo.html", context = {"question": questionInfo})

@login_required
@user_passes_test(isPartOfClass, redirect_field_name="homework-home")
def surveyEntry(request):
    if request.method == "POST":
        return redirect("homework-surveyInfo", code=request.POST.get("code"))
    return render(request, "homework/surveyEntry.html")

homework/templates/homework/add.html
{% extends 'homework/base.html'%}
{% load static %}

{% block content%}
<table>
    <tr>
        <th> Номер в класа </th>
        <th> Име, Фамилия </th>
    </tr>
    {% for user in users%}
    <tr {% for duty in activeDuties%} {% if duty.userConn.id == user.id%} class='active' {%endif%} {%endfor%}>
        {% if user.studentprofile.classNumber == 27 %}
        <td>Класен ръководител на 9."ж" клас</td>
        {% else %}
        <td>{{user.studentprofile.classNumber}}</td>
        {% endif %}
        <td>{{user.first_name}} {{user.last_name}}</td>
    </tr>
    {% endfor %}
</table>
{% if user.is_authenticated%}
    {% for duty in activeDuties%}
        {% if user.id == duty.userConn.id%}
            <h1 class='dueDateTag'>Имаш дежурство от {{duty.dateBegin}} до {{duty.dateEnd}}</h1>
            <div id='forms'>
                <form method='POST'>
                    {% csrf_token %}
                    {{ form.media }}
                    {{form.as_div}}
                    <input type='submit' value='Добавяне'>
                </form>
            </div>
        {% endif %}
    {% empty %}
    <h1 class='dueDateTag'>Нямаш активно дежурство тази седмица. Късметлия...</h1>
    {% endfor %}
{% else %}
<h1 class='dueDateTag'>Влез в профила си, за да видищ дали имаш дежурство тази седмица!</h1>
{% endif %}
{% endblock %}

homework/templates/homework/all.html
{% extends 'homework/base.html'%}
{% load static %}

<!-- * Вече не * Трябва да се оправи --> 
{%block content%}
    {% for assignment in assignments%}
        {% ifchanged assignment.dateDue%}
            <h1 class='dueDateTag'>{{assignment.dateDue}}</h1>
        {% endifchanged %}

        <div class="assignment-box">
            <div class="subject-info">
                <a href="{% url 'homework-assignment' assignment.id%}">
                    <h1>{{assignment.subject.name}}</h1>
                </a>
                <h3>{{assignment.subject.teacher}}</h3>
            </div>
            <div class="description-info">
                <p><span class='desc'>Тип на заданието:</span> {{assignment.typeOfAssignment}}</p>
                <p><span class='desc'>Описание:</span> {{assignment.description}}</p>
            </div>
        </div>
    {% empty %}
        <div class="assignment-box">
            <div class="subject-info" style='border: none'>
                <h1>Няма добавени задания!</h1>
            </div>
        </div>
    {% endfor %}
    {% if is_paginated %}
        <div class='pagination'>
            {% if page_obj.has_previous %}
                <a href="?page=1">&lt&lt</a>
                <a href="?page={{assignments.previous_page_number}}">&lt;</a>
            {% else %}
                <a class='disabled' href="?page=1">&lt&lt</a>
                <a class='disabled' href="?page={{assignments.previous_page_number}}">&lt;</a>
            {% endif %}
            <span class="current">
                Страница {{ page_obj.number }} от {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">&gt</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">&gt&gt</a>
            {% else %}
                <a class='disabled' href='#'>&gt</a>
                <a class='disabled' href='#'>&gt&gt</a>
            {% endif %}
            </div>
    {% endif %}
{%endblock%}

homework/templates/homework/assignment.html
{% extends 'homework/base.html'%}
{% load static %}

{%block content%}
    <!--Стилът за headerArticle е в homework/css/navigation.css. Мързи ме да ги сменям всеки път-->
    <h1 class='headerArticle'>Информация за задание с идентификационен №{{assignment.id}}</h1>
    <div class="assignment-box">
        <div class="subject-info">
            <h1>{{assignment.subject.name}}</h1>
            <h3>{{assignment.subject.teacher}}</h3>
        </div>
        <div class="description-info">
            <p><span class='desc'>Тип на заданието:</span> {{assignment.typeOfAssignment}}</p>
            <p><span class='desc'>Описание:</span> {{assignment.description}}</p>
            <p><span class='desc'>Добавено на:</span> {{assignment.dateAdded|date:"G:i ч. | j F Y"}}</p>
            <p><span class='desc'>Добавено от:</span> {{assignment.addedBy.first_name}} {{assignment.addedBy.last_name}}</p>
        </div>
    </div>
    {% if user.is_authenticated and assignment.addedBy.id == user.id %}
        <h1 class='dueDateTag'>Актуализиране на задание</h1>
        <div id='forms'>
            <form method='POST'>
                {% csrf_token %}
                {{ form.as_p }}
                <input type='submit' value='Актуализиране'>
            </form>
        </div>
    {% endif %}
{%endblock%}

homework/templates/homework/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Nata+Sans:wght@100..900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Advent+Pro:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% if title %} {{title}} {% else %} Default {% endif %}</title>
        <link rel="stylesheet" href={% static 'homework/css/reset.css'%}>
        <link rel="stylesheet" href={% static 'homework/css/navigation.css'%}>
        <link rel="stylesheet" href={% static 'homework/css/messages.css'%}>
        <link rel="stylesheet" href={% static 'homework/css/assignments.css'%}>
        <link rel="stylesheet" href={% static 'homework/css/modules.css'%}>
        <link rel="stylesheet" href={% static 'users/css/register.css'%}>
        <link rel="stylesheet" href={% static 'users/css/account-homework.css'%}>
        <link rel="stylesheet" href={% static 'homework/css/pagination.css'%}>
        <link rel="stylesheet" href={% static 'homework/css/survey.css'%}>
        <link rel='icon' href={% static 'homework/img/database-icon.png'%}>
        <script type='module' src={% static 'homework/js/firebase.js'%}></script>
    </head>
    <body>
        <header>
            <h1>База данни със заданията в 9. "ж" клас </h1>
            <h2>Трета ревизия на базата данни, направена изцяло от нас за целите на класа!</h2>
        </header>
        <nav>
            <img id='logo-img' src={% static 'homework/img/logo.png'%}>
            <a {% if homeActive %} id='active' {%endif%} href="{% url 'homework-home'%}">
                <img src="{% static 'homework/img/home-active.png'%}" alt="Начало">
                <span>Начало</span>
            </a>
            <a {% if tomorrowActive %} id='active' {%endif%} href="{% url 'homework-tomorrow'%}">
                <img style='width: 45px; height:45px' src="{% static 'homework/img/calendar-active.png'%}" alt="Утре">
                <span>Утре</span>
            </a>
            <a {% if allActive %} id='active' {%endif%} href="{% url 'homework-all'%}">
                <img src="{% static 'homework/img/database-active.png'%}" alt="Всички">
                <span>Всички</span>
            </a>
            <a {% if addActive %} id='active' {%endif%} href="{% url 'homework-add'%}">
                <img src="{% static 'homework/img/add.png'%}" alt="Всички">
                <span>Добавяне</span>
            </a>
            {% if user.is_authenticated %}
                {% if user.is_staff%}
                    <a {% if adminActive %} id='active' {%endif%} href="{% url 'admin:index'%}">
                        <img src="{% static 'homework/img/administrator.png'%}" alt="Администратор">
                        <span>Админ</span>
                    </a>
                {% endif %}
            {% endif %}
            <a href="{% url 'messages-main' %}">
                <img src="{% static 'homework/img/square.png'%}" alt="Тази седмица">
                <span>Чат</span>
            </a>
            <div class='auth'>
                {% if user.is_authenticated %}
                    <a id='logout' href="{% url 'users-logout' %}">
                        <img src="{% static 'homework/img/logout.png'%}" alt="Излезни">
                        <span>Излизане</span>
                    </a>
                    <a {% if profileViewOwn %} id='active' {%endif%} id='profileView' href="{% url 'users-profileinfo' user.id %}">
                        <img src="{% static 'homework/img/profile.png'%}" alt="Профил">
                        <span>Профил</span>
                    </a>
                {%else%}
                    <a {% if loginActive %} id='active' {%endif%} id='login' href="{% url 'users-login' %}">
                        <img style='width: 50px; height:50px' src="{% static 'homework/img/login.png'%}" alt="Влезни">
                        <span>Влизане</span>
                    </a>
                    <a {% if registerActive %} id='active' {%endif%} id='register' href="{% url 'users-register' %}">
                        <img src="{% static 'homework/img/registration.png'%}" alt="Регистрирай се">
                        <span>Регистриране</span>
                    </a>
                {%endif%}
            <div>
        </nav>
        <main>
            {% block content%}
            {% endblock %}
        </main>
        <footer>
            <span> &copy 2025 Версия {{VERSION}} / 9."ж" клас от Математическа гимназия "Академик Кирил Попов", Пловдив използва този сайт през учебната година 2025 / 2026 </span>
        </footer>
    </body>
</html>

homework/templates/homework/home.html
{% extends 'homework/base.html'%}
{% load static %}

{%block content%}
{% for message in messages%}
    <div class='website-messages'>
        <h2>{{message}}</h2>
    </div>
{%endfor%}
{% for message in activeMessages %}
    <div class="messagesTab {% if message.messageImportance == -1%}green{% endif %} {% if message.messageImportance == 0%}orange{% endif %} {% if message.messageImportance == 1%}red{% endif %}">
        <div class='messagesHeader'>
            <img src="
                {% if message.messageImportance == -1 %}
                    {% static 'homework/img/information.png' %}
                {% elif message.messageImportance == 0 %}
                    {% static 'homework/img/warning.png' %}
                {% elif message.messageImportance == 1 %}
                    {% static 'homework/img/crisis.png' %}
                {% endif %}
            ">
            <h1>{{message.messageLabel}}</h1>
        </div>
        <div class='messagesContent'>
            <p>{{message.messageText|linebreaksbr}}</p>
        </div>
    </div>
{% empty%}
    <div class="messagesTab green">
        <div class='messagesHeader'>
            <img src="{% static 'homework/img/information.png' %}">
            <h1>Няма активни съобщения</h1>
        </div>
        <div class='messagesContent'>
            <p>Няма нищо за показване тук...</p>
        </div>
    </div>
{% endfor %}

{%endblock%}

homework/templates/homework/success.html
{% extends 'homework/base.html'%}
{% load static %}

{% block content%}
    {% for message in messages%}
        {{message}}
    {%endfor%}
{% endblock %}

homework/templates/homework/surveyEntry.html
{% extends "homework/base.html" %}
{% load static %}

{% block content%}
<h1 class='dueDateTag'>Напишете кода на гласуването, даден от администратор</h1>
<h2 class='dueDateTag'>Гласувате като <b>{{user.first_name}} {{user.last_name}}, №{{user.studentprofile.classNumber}}<b></h2>
<form id='survey' method='POST'> 
    {% csrf_token %}
    <label class="text" for='code'>Код: </label>
    <input class="text" type='text' id='code' name='code'>
    <input type='submit' value='Въвеждане'>
</form>
{% endblock %}

homework/templates/homework/surveyInfo.html
{% extends "homework/base.html" %}
{% load static %}

{% block content%}
<style>
    #voteScreen
    {
        background: rgba(255, 255, 255, 0.2);
        border-radius: 16px;
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        backdrop-filter: blur(5px);
        -webkit-backdrop-filter: blur(5px);
        border: 1px solid rgba(255, 255, 255, 0.3);
        margin: 2%;
        padding: 20px;
    }
    #voteScreen > form > label
    {
        font-size: 20px;
    }
    #voteScreen > form > input[type='submit']
    {
        color: black;
        font-size:20px;
        padding: 5px;
        width:100%;
        margin-top:5px
    }
</style>
<h1 class='dueDateTag'>Участие в гласуванe с код <b>{{question.questionCode}}</b></h1>
<div id='voteScreen'>
    <h1 class='dueDateTag'>{{question.question}}</h1>
    <form action="{% url 'homework-home' %}" method="post">
        {%csrf_token%}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choices_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choiceText }}</label><br>
        {% endfor %}
        <input type='submit' value='Гласуване'>
    </form>
</div>
{% endblock %}

homework/templates/homework/tomorrow.html
{% extends 'homework/base.html'%}
{% load static %}

<!-- * Вече не * Трябва да се оправи --> 
{%block content%}

    {% for assignment in assignments%}
        {% ifchanged assignment.dateDue%}
            <h1 class='dueDateTag'>Задания за {{assignment.dateDue}}</h1>
        {% endifchanged %}
        <div class="assignment-box">
            <div class="subject-info">
                <a href="{% url 'homework-assignment' assignment.id%}">
                    <h1>{{assignment.subject.name}}</h1>
                </a>
                <h3>{{assignment.subject.teacher}}</h3>
            </div>
            <div class="description-info">
                <p><span class='desc'>Тип на заданието:</span> {{assignment.typeOfAssignment}}</p>
                <p><span class='desc'>Описание:</span> {{assignment.description}}</p>
            </div>
        </div>
    {% empty %}
        <div class="assignment-box">
            <div class="subject-info" style='border: none'>
                <h1>Няма добавена домашна за утре!</h1>
            </div>
        </div>
    {% endfor %}
    {% if is_paginated %}
        <div class='pagination'>
            {% if page_obj.has_previous %}
                <a href="?page=1">&lt &lt</a>
                <a href="?page={{assignments.previous_page_number}}">&lt;</a>
            {% else %}
                <a class='disabled' href="?page=1">&lt&lt</a>
                <a class='disabled' href="?page={{assignments.previous_page_number}}">&lt;</a>
            {% endif %}
            <span class="current">
                Страница {{ page_obj.number }} от {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">&gt</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">&gt&gt</a>
            {% else %}
                <a class='disabled' href='#'>&gt</a>
                <a class='disabled' href='#'>&gt&gt</a>
            {% endif %}
            </div>
    {% endif %}
{%endblock%}